### ISSUE TITLE
MY ACCOUNT

### ISSUE THREAD

**Issue by macy125** [wgimson/QRdly#38] opened 2021-10-06 02:34 UTC
https://serene-everglades-65051.herokuapp.com/account

Deleting account should not be an option.

**Comment by wgimson** [comment] 2022-04-16 22:14
@macy125 
I believe this is an old duplicate of [Issue 54](https://github.com/wgimson/QRdly/issues/54)

If so we should close this one.

**Closed** 2022-04-27 01:19 UTC
Labels: bug, edits & enhancements
