### ISSUE TITLE
ACCOUNT MGMT

### ISSUE THREAD

**Issue by macy125** [wgimson/QRdly#46] opened 2021-10-14 01:26 UTC
https://serene-everglades-65051.herokuapp.com/account

We don't need e-mail verification because they'll be registering

**Comment by wgimson** [comment] 2021-11-04 03:46
@macy125 @alexgimson86 

This is waiting on a detailed workflow for customer onboarding.

**Comment by wgimson** [comment] 2022-04-16 22:15
I believe this is an old duplicate of https://github.com/wgimson/QRdly/issues/54

If so we should close this one.

**Closed** 2022-04-27 01:20 UTC
Labels: edits & enhancements
